[build]
publish="public/"
command="yarn build"

[functions]
directory="functions/"
included_files=["templates/**"]

[[redirects]]
from="/auth"
to="/.netlify/functions/auth"
status=200

[[redirects]]
from="/api/profile"
to="/.netlify/functions/profile"
status=200

[[redirects]]
from="/api/user"
to="/.netlify/functions/user"
status=200

[[redirects]]
from="/api/links"
to="/.netlify/functions/link"
status=200

[[redirects]]
from="/api/completions"
to="/.netlify/functions/complete"
status=200

[[redirects]]
from="/*"
to="/index.html"
status=200