[build]
publish="public/"
command="yarn build"

[functions]
directory="functions/"
included_files=["templates/**", "weeks.json", "pages.json", "fold.min.css"]

[[redirects]]
from="/auth"
to="/.netlify/functions/auth"
status=200

[[redirects]]
from="/api/complete"
to="/.netlify/functions/complete"
status=200

[[redirects]]
from="/api/progress"
to="/.netlify/functions/progress"
status=200

[[redirects]]
from="/api/login"
to="/.netlify/functions/login"
status=200

[[redirects]]
from="/read"
to="/.netlify/functions/serve-list"
status=200

[[redirects]]
from="/"
to="/.netlify/functions/cookie-tester"
status=200