[build]
publish="public/"
command="yarn build"

[functions]
directory="functions/"
included_files=["templates/**", "weeks.json", "pages.json", "fold.min.css"]

[[redirects]]
from="/auth"
to="/.netlify/functions/auth"
status=200

[[redirects]]
from="/api/profile"
to="/.netlify/functions/profile"
status=200

[[redirects]]
from="/api/user"
to="/.netlify/functions/user"
status=200

[[redirects]]
from="/api/completions"
to="/.netlify/functions/complete"
status=200

[[redirects]]
from="/read"
to="/.netlify/functions/serve-list"
status=200